/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.*;

import java.net.http.HttpClient;

public class SimpleServerTest {
    
    @Test 
    public void testSimpleServer() {
        System.out.println("implementar aqui um cliente que "
                + "faça as chamadas ao servidor");
        
        HttpClient client = HttpClient.newBuilder().build();
        
        
    }
}
